version: '3'

services:
    mysql_db:
       # container_name: mysql_db
        image: mysql
        ports:
          - '3306:3306'
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: mysql_db
          MYSQL_DATABASE: todo
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        networks: 
          - concourse_backend

    # app:
    #    image: todo-app-tag
    #     container_name: 'todo-services'
    #     depends_on:
    #         - mysql_db
    #     ports:
    #         - '8089:8080'


networks: 
  concourse_backend:
    external: true